import React from 'react';
import type { PresenceMember } from '@lexprompt/core';
import { UNRESOLVED_ACTOR_SENTENCE, type DispositionAudience } from '../lib/findingOutcome';

export interface PresenceRosterProps {
  /** The server's roster for this subscription, as it last stated it. */
  members: PresenceMember[];
  /** This browser's own user id, so it can be left out — see below. */
  meId?: string;
  /** How an id becomes a name. The same `DispositionAudience` every
   *  attribution surface takes, so there is one resolver on this screen
   *  rather than one per component (P32). */
  audience?: DispositionAudience;
}

/**
 * WHO ELSE IS LOOKING AT THIS, RIGHT NOW (§8, S6, Task 23).
 *
 * ## It is not a disposition, and nothing about it may read like one
 *
 * A face here means *"somebody is looking at this"* and never *"somebody has
 * checked this"*. That is why it uses the presence colour rather than any
 * state or outcome ink, why the tooltip and the screen-reader text both say
 * "is viewing" in words, and why it carries no tick, no flag and no cross.
 * If any surface built on this could be misread as a verification, that is
 * the defect — the whole app exists to keep "a person decided this" and
 * "the machine said this" apart, and "a person is HERE" is a third thing
 * that must not borrow either one's clothes.
 *
 * ## It is advisory, and it says so
 *
 * An absent name does not mean nobody is there; a present name is a claim
 * about a few seconds ago. The title says so in a sentence a reader can act
 * on, because a roster that looks authoritative is one somebody defers to.
 *
 * ## You are not on it — and if it does not know who you are, it says
 * nothing
 *
 * You already know you are here. A roster including you is a roster that is
 * never empty, which makes *"is anyone else here?"* — the one question it
 * exists to answer — unanswerable at a glance.
 *
 * `meId` is `profile?.id ?? ''` at the caller, so before `GET /v1/me`
 * answers it matches nobody and the filter excluded nothing — putting YOU on
 * the roster this docstring says you must never be on, with your own
 * initials, for as long as the profile took. Nothing renders until the tab
 * knows whose it is: "who else is here" is not a question that can be
 * answered without that, and a blank for a frame is the honest form of not
 * knowing.
 *
 * ## Nothing renders when nobody is here
 *
 * No placeholder, no "0 viewers". An empty roster is the ordinary case, and
 * a permanent empty chip is a thing readers stop seeing — which would take
 * the non-empty case with it.
 */
export function PresenceRoster({ members, meId, audience }: PresenceRosterProps) {
  if (!meId) return null;
  const others = members.filter(m => m.userId !== meId);
  if (others.length === 0) return null;

  return (
    <div
      data-presence-roster
      className="flex items-center gap-1"
      // ADVISORY, in a sentence. The roster expires 15 seconds after a
      // person's last heartbeat, so this is true of the whole surface and
      // not only of a stale one.
      title="People viewing this review now. Presence is approximate and clears within seconds of somebody leaving."
    >
      {others.map(member => (
        <PresenceDot key={member.userId} member={member} audience={audience} />
      ))}
    </div>
  );
}

/**
 * One colleague.
 *
 * `nameFor` returns `undefined` for an id the directory does not hold, and
 * this renders "?" with the words "someone this workspace does not name" —
 * NEVER the raw id, which says nothing to a reader while looking like it
 * should, and never an invented name. The same rule `dispositionLabel`
 * follows for an actor (R-GP5, P32).
 */
function PresenceDot({ member, audience }: { member: PresenceMember; audience?: DispositionAudience }) {
  const name = audience?.nameOf(member.userId);
  // FROM THE SAME RESOLVER AS THE NAME. This read `userInitials` off the
  // module directly while taking the name from the injected `audience`, so
  // one component held two resolvers where P32's rule is one — and a caller
  // that supplied an audience got a name from it and initials from
  // somewhere else, which is how "R. Okafor" comes to wear "?".
  const initials = audience?.initialsOf(member.userId);
  const label = name ?? UNRESOLVED_ACTOR_SENTENCE;
  return (
    <span
      data-presence-member={member.userId}
      // The COMPLETE class strings, written out. A name built by
      // interpolation (`bg-presence-${…}`) is never generated by Tailwind's
      // compiler and renders as no colour at all, with no error and no
      // failing test (CLAUDE.md).
      className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-presence-tint text-presence border border-presence font-mono text-pin uppercase"
      title={`${label} is viewing this review`}
    >
      <span aria-hidden="true">{initials ?? '?'}</span>
      {/* The only text a screen reader gets, and it says VIEWING. A bare
          set of initials beside a clause would be read as an attribution. */}
      <span className="sr-only">{`${label} is viewing this review`}</span>
    </span>
  );
}

export interface ClausePresenceProps {
  /** The colleagues whose selected clause is this one. */
  members: PresenceMember[];
  audience?: DispositionAudience;
}

/**
 * THE MARKER ON A CLAUSE SOMEBODY ELSE HAS SELECTED.
 *
 * The owner's requirement is *"ideally down to the particular clause"*, and
 * this is that. It is deliberately the same vocabulary as the roster above —
 * one dot, one colour, one sentence — rather than a second design, so a
 * reader learns "this shape means a person is here" once.
 *
 * It sits in the clause rail BESIDE the status icon rather than replacing
 * it: the status icon says what the machine and the reviewer have made of a
 * clause, and this says who is reading it. Two facts, two marks, never one
 * mark carrying both.
 */
export function ClausePresence({ members, audience }: ClausePresenceProps) {
  if (members.length === 0) return null;
  const names = members
    .map(m => audience?.nameOf(m.userId) ?? UNRESOLVED_ACTOR_SENTENCE)
    .join(', ');
  const sentence = members.length === 1
    ? `${names} is viewing this clause`
    : `${names} are viewing this clause`;
  return (
    <span
      data-presence
      className="inline-flex items-center gap-0.5 shrink-0"
      title={sentence}
    >
      {members.map(member => (
        <span
          key={member.userId}
          data-presence-member={member.userId}
          className="inline-flex items-center justify-center w-4 h-4 rounded-full bg-presence-tint text-presence font-mono text-pin uppercase leading-none"
          aria-hidden="true"
        >
          {audience?.initialsOf(member.userId)?.slice(0, 1) ?? '?'}
        </span>
      ))}
      <span className="sr-only">{sentence}</span>
    </span>
  );
}
