import type { Citation, ReviewRun, RiskLevel } from '../../types';
import { describeFindingOutcome, exportSummaryLine, verificationLabel, noteLines } from '../../lib/findingOutcome';
import { findingsKeyFor } from '../../lib/reviewTarget';

export interface ReportRow {
  title: string;
  summary: string;
  riskLevel?: RiskLevel;
  riskAnalysis?: string;
  citations: Citation[];
  verificationLabel: string | null;
  /** Important 3 (spec §6: "a flagged finding carries its flag and any
   *  note"): one formatted, attributed line per note. Shared with the CSV
   *  exporter via `findingOutcome.ts`'s `noteLines` so the two cannot
   *  disagree about what a note looks like once it leaves the app. */
  notes: string[];
}

/**
 * Derives the report's row data from a run, independent of the docx
 * document construction below. This is the part where the row-level
 * decisions live — most importantly, that a clause whose extraction failed
 * still gets a row that says so, rather than being silently dropped. A
 * report that omits a failed clause reads as "checked, nothing found",
 * which is worse than an honest failure notice.
 */
export function buildReportRows(run: ReviewRun, docId: string): ReportRow[] {
  // A collection review's findings live under the COLLECTION id, not the
  // document id — `findingsKeyFor` resolves that (and is a no-op for an
  // ordinary document review, where it just returns `docId` back). Keying
  // directly by `docId` here used to make a collection review's export
  // silently empty (Step 0 of this task).
  const findings = run.findings[findingsKeyFor(run.target, docId)];
  if (!findings) return [];

  return run.templateSnapshot.clauses.map(clause => {
    const finding = findings[clause.id];

    if (!finding || finding.status !== 'done') {
      return {
        title: clause.title,
        summary: describeFindingOutcome(finding),
        citations: [],
        verificationLabel: verificationLabel(finding),
        notes: noteLines(finding),
      };
    }

    return {
      title: clause.title,
      summary: finding.summary ?? '',
      riskLevel: finding.riskLevel,
      riskAnalysis: finding.riskAnalysis,
      citations: finding.citations,
      verificationLabel: verificationLabel(finding),
      notes: noteLines(finding),
    };
  });
}

/** Maps a risk level to the same pastel cell-shading colours the original
 *  report used. Anything without a recognised level (including the "could
 *  not be reviewed" rows, which carry no riskLevel) gets no risk row at all. */
function riskFill(level: RiskLevel): string {
  if (level === 'High') return 'FFCCCC';
  if (level === 'Medium') return 'FFF4CC';
  if (level === 'Low') return 'CCFFCC';
  return 'FFFFFF';
}

function stripExtension(name: string): string {
  return name.replace(/\.[^./\\]+$/, '');
}

/**
 * Builds the `docx` `Document` object for a report: one bordered table per
 * clause, matching the structure of the original (deleted) ResultsView's
 * exporter — a header row, a labelled row for anything a human hasn't
 * verified, a summary row, an optional risk row (shaded by level), an
 * evidence header, and one numbered row per citation (or a "no reference
 * found" placeholder when there are none).
 *
 * Split out from `exportDocx` so the document construction — including
 * whether the verification label actually reaches the table, which
 * `buildReportRows` alone cannot prove — is exercised directly in tests via
 * `Packer.toBuffer` and a zip read of `word/document.xml`, rather than only
 * asserting on the intermediate `ReportRow[]` data.
 *
 * `docx` is dynamically imported so it never enters the app's entry chunk —
 * most sessions never export a report, and the library is large enough that
 * a top-level import would make every user pay for it on first load.
 */
export async function buildReportDocument(rows: ReportRow[], docName: string, summaryLine: string) {
  const {
    Document, Paragraph, TextRun, HeadingLevel, AlignmentType,
    Table, TableRow, TableCell, WidthType, BorderStyle,
  } = await import('docx');

  const children: (InstanceType<typeof Paragraph> | InstanceType<typeof Table>)[] = [
    new Paragraph({
      text: `Review Report: ${docName}`,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),
    new Paragraph({
      text: `Generated by LexPrompt on ${new Date().toLocaleDateString()}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 500 },
    }),
    new Paragraph({
      children: [new TextRun({ text: summaryLine, bold: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ];

  const cellMargins = { top: 100, bottom: 100, left: 100, right: 100 };

  for (const row of rows) {
    const tableRows = [];

    // Header
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: row.title, bold: true, color: 'FFFFFF' })] })],
          columnSpan: 2,
          shading: { fill: '333333' },
          margins: cellMargins,
        }),
      ],
    }));

    // A labelled row for anything a human has not verified. Placed above the
    // summary, not below the evidence, because a reader skimming the report
    // must meet the caveat before they read the claim.
    if (row.verificationLabel) {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: row.verificationLabel, bold: true })] })],
            columnSpan: 2,
            shading: { fill: 'FFF4CC' },
            margins: cellMargins,
          }),
        ],
      }));
    }

    // Notes (Important 3 — spec §6): each one its own row, right after the
    // verification caveat and before the summary, for the same reason the
    // label sits there — a reader skimming must meet a human's own comment
    // before the AI-authored claim.
    for (const note of row.notes) {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: note })] })],
            columnSpan: 2,
            shading: { fill: 'EEF2FF' },
            margins: cellMargins,
          }),
        ],
      }));
    }

    // Summary
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [
            new Paragraph({ children: [new TextRun({ text: 'Summary', bold: true })] }),
            new Paragraph({ text: row.summary }),
          ],
          columnSpan: 2,
          margins: cellMargins,
        }),
      ],
    }));

    // Risk (only when the clause actually carries a risk level)
    if (row.riskLevel) {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: 'RISK RATING', bold: true })] }),
              new Paragraph({ children: [new TextRun({ text: row.riskLevel.toUpperCase(), bold: true })] }),
            ],
            width: { size: 20, type: WidthType.PERCENTAGE },
            shading: { fill: riskFill(row.riskLevel) },
            verticalAlign: 'center',
            margins: cellMargins,
          }),
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: 'Risk Analysis', bold: true })] }),
              new Paragraph({ text: row.riskAnalysis || 'No specific analysis provided.' }),
            ],
            width: { size: 80, type: WidthType.PERCENTAGE },
            margins: cellMargins,
          }),
        ],
      }));
    }

    // Evidence header
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: 'Evidence', bold: true })] })],
          columnSpan: 2,
          shading: { fill: 'EEEEEE' },
          margins: { top: 50, bottom: 50, left: 100, right: 100 },
        }),
      ],
    }));

    // Citations, numbered — or an honest placeholder when there are none.
    if (row.citations.length > 0) {
      row.citations.forEach((cite, idx) => {
        tableRows.push(new TableRow({
          children: [
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: `Ref ${idx + 1}`, bold: true })] })],
              width: { size: 15, type: WidthType.PERCENTAGE },
              margins: { top: 50, bottom: 50, left: 50, right: 50 },
            }),
            new TableCell({
              children: [new Paragraph({
                children: [
                  new TextRun({ text: `"${cite.quote}"`, italics: true }),
                  ...(cite.page !== undefined
                    ? [new TextRun({ text: `  (p. ${cite.page})`, italics: false, color: '666666' })]
                    : []),
                ],
              })],
              width: { size: 85, type: WidthType.PERCENTAGE },
              margins: { top: 50, bottom: 50, left: 50, right: 50 },
            }),
          ],
        }));
      });
    } else {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ text: '-' })],
            width: { size: 15, type: WidthType.PERCENTAGE },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'No Relevant Reference Found', italics: true })] })],
            width: { size: 85, type: WidthType.PERCENTAGE },
          }),
        ],
      }));
    }

    children.push(new Table({
      rows: tableRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
      },
    }));
    children.push(new Paragraph({ text: '', spacing: { after: 300 } }));
  }

  return new Document({ sections: [{ properties: {}, children }] });
}

/**
 * Builds and downloads a .docx report for one document in a run. See
 * `buildReportRows` for the row-level decisions and `buildReportDocument`
 * for how those rows become the actual `docx` document.
 */
export async function exportDocx(run: ReviewRun, docId: string, docName: string): Promise<void> {
  const rows = buildReportRows(run, docId);
  // Fail-loudly rule, applied to the surface where the whole app's founding
  // defect was first learned (CLAUDE.md): a review that genuinely has no
  // findings for this document/collection must say so, rather than handing
  // back a technically-valid .docx with a title and a summary line but zero
  // clause tables — a document a lawyer could send without ever noticing it
  // says nothing.
  if (rows.length === 0) {
    throw new Error(`No findings to export for ${docName}. This review has no results to report yet.`);
  }
  // Important 4: this report covers ONE document (`buildReportRows(run,
  // docId)` above), so its header summary must count only that document's
  // findings — not `exportSummaryLine(run.findings)`, which counts the
  // whole run. The CSV export (`buildTabularCsv`) genuinely does cover every
  // document, so its whole-run summary is correct as-is; scoping only
  // belongs here, at the one place that reports on a single document.
  const docSummary = exportSummaryLine({ [docId]: run.findings[findingsKeyFor(run.target, docId)] ?? {} });
  const doc = await buildReportDocument(rows, docName, docSummary);

  const { Packer } = await import('docx');
  const blob = await Packer.toBlob(doc);

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${stripExtension(docName)}_Report.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
