import type { ReviewRun, RiskLevel } from '../../types';
import { describeFindingOutcome } from '../../lib/findingOutcome';

export interface ReportRow {
  title: string;
  summary: string;
  riskLevel?: RiskLevel;
  riskAnalysis?: string;
  citations: string[];
}

/**
 * Derives the report's row data from a run, independent of the docx
 * document construction below. This is the part worth unit-testing: the
 * table-building call into the `docx` library is not usefully testable
 * (it's all library calls), but the decision of what each row says is where
 * the actual logic lives — most importantly, that a clause whose extraction
 * failed still gets a row that says so, rather than being silently dropped.
 * A report that omits a failed clause reads as "checked, nothing found",
 * which is worse than an honest failure notice.
 */
export function buildReportRows(run: ReviewRun, docId: string): ReportRow[] {
  const findings = run.findings[docId];
  if (!findings) return [];

  return run.templateSnapshot.clauses.map(clause => {
    const finding = findings[clause.id];

    if (!finding || finding.status !== 'done') {
      return {
        title: clause.title,
        summary: describeFindingOutcome(finding),
        citations: [],
      };
    }

    return {
      title: clause.title,
      summary: finding.summary ?? '',
      riskLevel: finding.riskLevel,
      riskAnalysis: finding.riskAnalysis,
      citations: finding.citations,
    };
  });
}

/** Maps a risk level to the same pastel cell-shading colours the original
 *  report used. Anything without a recognised level (including the "could
 *  not be reviewed" rows, which carry no riskLevel) gets no risk row at all. */
function riskFill(level: RiskLevel): string {
  if (level === 'High') return 'FFCCCC';
  if (level === 'Medium') return 'FFF4CC';
  if (level === 'Low') return 'CCFFCC';
  return 'FFFFFF';
}

function stripExtension(name: string): string {
  return name.replace(/\.[^./\\]+$/, '');
}

/**
 * Builds and downloads a .docx report: one bordered table per clause,
 * matching the structure of the original (deleted) ResultsView's exporter —
 * a header row, a summary row, an optional risk row (shaded by level), an
 * evidence header, and one numbered row per citation (or a "no reference
 * found" placeholder when there are none).
 *
 * `docx` is dynamically imported so it never enters the app's entry chunk —
 * most sessions never export a report, and the library is large enough that
 * a top-level import would make every user pay for it on first load.
 */
export async function exportDocx(run: ReviewRun, docId: string, docName: string): Promise<void> {
  const rows = buildReportRows(run, docId);

  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
    Table, TableRow, TableCell, WidthType, BorderStyle,
  } = await import('docx');

  const children: (InstanceType<typeof Paragraph> | InstanceType<typeof Table>)[] = [
    new Paragraph({
      text: `Review Report: ${docName}`,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),
    new Paragraph({
      text: `Generated by LexPrompt on ${new Date().toLocaleDateString()}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 500 },
    }),
  ];

  const cellMargins = { top: 100, bottom: 100, left: 100, right: 100 };

  for (const row of rows) {
    const tableRows = [];

    // Header
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: row.title, bold: true, color: 'FFFFFF' })] })],
          columnSpan: 2,
          shading: { fill: '333333' },
          margins: cellMargins,
        }),
      ],
    }));

    // Summary
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [
            new Paragraph({ children: [new TextRun({ text: 'Summary', bold: true })] }),
            new Paragraph({ text: row.summary }),
          ],
          columnSpan: 2,
          margins: cellMargins,
        }),
      ],
    }));

    // Risk (only when the clause actually carries a risk level)
    if (row.riskLevel) {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: 'RISK RATING', bold: true })] }),
              new Paragraph({ children: [new TextRun({ text: row.riskLevel.toUpperCase(), bold: true })] }),
            ],
            width: { size: 20, type: WidthType.PERCENTAGE },
            shading: { fill: riskFill(row.riskLevel) },
            verticalAlign: 'center',
            margins: cellMargins,
          }),
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: 'Risk Analysis', bold: true })] }),
              new Paragraph({ text: row.riskAnalysis || 'No specific analysis provided.' }),
            ],
            width: { size: 80, type: WidthType.PERCENTAGE },
            margins: cellMargins,
          }),
        ],
      }));
    }

    // Evidence header
    tableRows.push(new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: 'Evidence', bold: true })] })],
          columnSpan: 2,
          shading: { fill: 'EEEEEE' },
          margins: { top: 50, bottom: 50, left: 100, right: 100 },
        }),
      ],
    }));

    // Citations, numbered — or an honest placeholder when there are none.
    if (row.citations.length > 0) {
      row.citations.forEach((cite, idx) => {
        tableRows.push(new TableRow({
          children: [
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: `Ref ${idx + 1}`, bold: true })] })],
              width: { size: 15, type: WidthType.PERCENTAGE },
              margins: { top: 50, bottom: 50, left: 50, right: 50 },
            }),
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: `"${cite}"`, italics: true })] })],
              width: { size: 85, type: WidthType.PERCENTAGE },
              margins: { top: 50, bottom: 50, left: 50, right: 50 },
            }),
          ],
        }));
      });
    } else {
      tableRows.push(new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ text: '-' })],
            width: { size: 15, type: WidthType.PERCENTAGE },
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: 'No Relevant Reference Found', italics: true })] })],
            width: { size: 85, type: WidthType.PERCENTAGE },
          }),
        ],
      }));
    }

    children.push(new Table({
      rows: tableRows,
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'EEEEEE' },
      },
    }));
    children.push(new Paragraph({ text: '', spacing: { after: 300 } }));
  }

  const doc = new Document({ sections: [{ properties: {}, children }] });
  const blob = await Packer.toBlob(doc);

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${stripExtension(docName)}_Report.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
